import os
import ssl
import certifi
import io
import logging
from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from google import genai
from google.genai import types
from dotenv import load_dotenv

# Set up explicit terminal logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("gemini-backend")
# Forces the global SSL environment context to bind to certifi's active certificate authority pool
os.environ["SSL_CERT_FILE"] = certifi.where()
ssl._create_default_https_context = ssl._create_unverified_context

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")
if not API_KEY:
    logger.error("❌ CRITICAL: GEMINI_API_KEY environment variable is empty or missing!")

app = FastAPI(title="Gemini Clone Backend")


app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize the modern SDK client explicitly passing the token instance
client = genai.Client(api_key=API_KEY)

# Use the standardized production production targets 
MODEL_ID = "gemini-2.5-flash"

@app.post("/api/chat")
async def chat_with_search(prompt: str = Form(...)):
    try:
        logger.info(f"Received query: {prompt}")
        
        config = types.GenerateContentConfig(
            tools=[types.Tool(google_search=types.GoogleSearch())]
        )
        
        response = client.models.generate_content(
            model=MODEL_ID,
            contents=prompt,
            config=config
        )
        
        # Pull grounding references safely
        metadata = getattr(response.candidates[0], 'grounding_metadata', None)
        sources = []
        search_queries = []
        
        if metadata:
            search_queries = getattr(metadata, 'web_search_queries', [])
            chunks = getattr(metadata, 'grounding_chunks', [])
            if chunks:
                for chunk in chunks:
                    if chunk.web:
                        sources.append({"title": chunk.web.title, "url": chunk.web.uri})

        return {
            "text": response.text,
            "search_queries": search_queries,
            "sources": sources
        }
    except Exception as e:
        logger.exception("Exception caught during /api/chat execution trace:")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/upload-and-analyze")
async def upload_and_analyze(prompt: str = Form(...), file: UploadFile = File(...)):
    temp_filename = f"temp_{file.filename}"
    try:
        logger.info(f"Processing uploaded file asset: {file.filename}")
        file_bytes = await file.read()
        
        with open(temp_filename, "wb") as f:
            f.write(file_bytes)
            
        uploaded_file = client.files.upload(
            file=temp_filename,
            mime_type=file.content_type
        )
        
        response = client.models.generate_content(
            model=MODEL_ID,
            contents=[uploaded_file, prompt]
        )
        
        return {"text": response.text}
    except Exception as e:
        logger.exception("Exception caught during /api/upload-and-analyze execution trace:")
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if os.path.exists(temp_filename):
            os.remove(temp_filename)

@app.post("/api/generate-image")
async def generate_image(prompt: str = Form(...)):
    try:
        logger.info(f"Generating image content for: {prompt}")
        
        # Switch model target to the dedicated text-to-image engine
        response = client.models.generate_images(
            model="imagen-3.0-generate-002",
            prompt=prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                output_mime_type="image/jpeg",
                aspect_ratio="1:1", # Automatically targets your 1080x1080 resolution request
                person_generation="ALLOW_ADULT"
            )
        )
        
        # Pull the generated bytes from the Imagen output structure
        generated_image = response.generated_images[0]
        image_bytes = generated_image.image.image_bytes
        
        return StreamingResponse(io.BytesIO(image_bytes), media_type="image/jpeg")
                
    except Exception as e:
        logger.exception("Exception caught during /api/generate-image execution trace:")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)